Document: creshmap
Title: Debian creshmap Manual
Author: <insert document author here>
Abstract: This manual describes what creshmap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/creshmap/creshmap.sgml.gz

Format: postscript
Files: /usr/share/doc/creshmap/creshmap.ps.gz

Format: text
Files: /usr/share/doc/creshmap/creshmap.text.gz

Format: HTML
Index: /usr/share/doc/creshmap/html/index.html
Files: /usr/share/doc/creshmap/html/*.html
